name: Terraform Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  apply:
    name: 'terraform-apply'
    runs-on: ubuntu-latest

    steps:
    - name: 'terraform-apply'
      run: echo "Hello Terraform Apply!"